
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Switch to a different network
 * 
 * This command switches the active network, creating a new adapter if needed.
 * The adapter is cached for future use.
 * **PHASE 3.4**: Now emits chainChanged event to all connected dApp windows.
 * 
 * # Arguments
 * 
 * * `app` - Tauri app handle (for event emission)
 * * `state` - Application state
 * * `request` - Network switch request
 * 
 * # Returns
 * 
 * * `Ok(())` - Network switched successfully
 * * `Err(String)` - Error message
 * 
 * # Example (from frontend)
 * 
 * ```typescript
 * await invoke('switch_network', {
 * request: {
 * networkId: 'ethereum-mainnet',
 * rpcUrl: 'https://eth.llamarpc.com',
 * chainId: 1
 * }
 * });
 * ```
 */
async switchNetwork(request: SwitchNetworkRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_network", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get native token balance for an address
 * 
 * # Arguments
 * 
 * * `state` - Application state
 * * `address` - Ethereum address (0x...)
 * 
 * # Returns
 * 
 * * `Ok(BalanceResponse)` - Balance information
 * * `Err(String)` - Error message
 * 
 * # Example (from frontend)
 * 
 * ```typescript
 * const balance = await invoke('get_balance', {
 * address: '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045'
 * });
 * console.log(`Balance: ${balance.balance_eth} ${balance.symbol}`);
 * ```
 */
async getBalance(address: string) : Promise<Result<BalanceResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_balance", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current network information
 * 
 * # Arguments
 * 
 * * `state` - Application state
 * 
 * # Returns
 * 
 * * `Ok(NetworkInfoResponse)` - Network information
 * * `Err(String)` - Error message
 * 
 * # Example (from frontend)
 * 
 * ```typescript
 * const info = await invoke('get_network_info');
 * console.log(`Connected to: ${info.network_name} (Chain ID: ${info.chain_id})`);
 * ```
 */
async getNetworkInfo() : Promise<Result<NetworkInfoResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_network_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current chain ID
 * 
 * # Arguments
 * 
 * * `state` - Application state
 * 
 * # Returns
 * 
 * * `Ok(u64)` - Chain ID
 * * `Err(String)` - Error message
 * 
 * # Example (from frontend)
 * 
 * ```typescript
 * const chainId = await invoke('get_chain_id');
 * console.log(`Chain ID: ${chainId}`);
 * ```
 */
async getChainId() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chain_id") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current block number
 * 
 * # Arguments
 * 
 * * `state` - Application state
 * 
 * # Returns
 * 
 * * `Ok(u64)` - Block number
 * * `Err(String)` - Error message
 * 
 * # Example (from frontend)
 * 
 * ```typescript
 * const blockNumber = await invoke('get_block_number');
 * console.log(`Latest block: ${blockNumber}`);
 * ```
 */
async getBlockNumber() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_block_number") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get supported networks
 * 
 * Returns a list of all supported network configurations.
 * 
 * # Arguments
 * 
 * * `state` - Application state
 * 
 * # Returns
 * 
 * * `Ok(Vec<NetworkConfig>)` - List of supported networks
 * * `Err(String)` - Error message
 * 
 * # Example (from frontend)
 * 
 * ```typescript
 * const networks = await invoke('get_supported_networks');
 * console.log(`Supported networks: ${networks.length}`);
 * ```
 */
async getSupportedNetworks() : Promise<Result<NetworkConfig[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_supported_networks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generic RPC request bypass
 * 
 * Routes an RPC request to a specific chain via the backend's Alloy adapters.
 * This bypasses frontend CORS restrictions.
 */
async ethRequest(chainId: string, method: string, params: any[]) : Promise<Result<any, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("eth_request", { chainId, method, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generic HTTP proxy for whitelisted domains to bypass CORS in WebWorkers
 */
async proxyRequest(url: string, method: string, headers: Partial<{ [key in string]: string }> | null, body: any | null) : Promise<Result<any, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("proxy_request", { url, method, headers, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTokenPrice() : Promise<Result<TokenPriceResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_token_price") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshTokenPrices() : Promise<Result<TokenPriceResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_token_prices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTokenBalance(tokenAddress: string, walletAddress: string) : Promise<Result<TokenBalanceResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_token_balance", { tokenAddress, walletAddress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTokenMetadata(tokenAddress: string) : Promise<Result<TrackedToken, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_token_metadata", { tokenAddress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addCustomToken(tokenAddress: string) : Promise<Result<TrackedToken, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_custom_token", { tokenAddress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeCustomToken(tokenAddress: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_custom_token", { tokenAddress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrackedTokens() : Promise<Result<TrackedToken[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tracked_tokens") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export current persisted state
 * 
 * Returns the raw JSON content of the state file.
 * Useful for debugging or backups.
 */
async exportState() : Promise<Result<PersistedStateExport, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset persisted state
 * 
 * Deletes the state file. The app will use defaults on next restart.
 * Note: This does not reset the currently running in-memory state.
 */
async resetState() : Promise<Result<null, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current user preferences
 * 
 * Returns the user preferences from the persisted state.
 */
async getUserPreferences() : Promise<Result<UserPreferences, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_user_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update user preferences
 * 
 * Saves the updated user preferences to the persisted state.
 */
async updateUserPreferences(preferences: UserPreferences) : Promise<Result<null, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_user_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate transaction parameters
 */
async validateTransaction(request: ValidateTransactionRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_transaction", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Estimate gas for a simple transfer
 */
async estimateGasSimple(from: string, to: string, amount: string, tokenAddress: string | null, data: string | null) : Promise<Result<EstimateGasResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("estimate_gas_simple", { from, to, amount, tokenAddress, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build transaction
 */
async buildTransaction(request: BuildTransactionRequest) : Promise<Result<BuildTransactionResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_transaction", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sign transaction
 */
async signTransaction(request: SignTransactionRequest) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sign_transaction", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send transaction
 */
async sendTransaction(request: SendTransactionRequest) : Promise<Result<TransactionResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_transaction", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new wallet with BIP-39 mnemonic
 * 
 * Generates a new wallet with the specified number of words.
 * The wallet starts locked - user must call `unlock_wallet` to use it.
 * 
 * # Arguments
 * 
 * * `password` - Password for encrypting the seed
 * * `word_count` - Number of words (12 or 24)
 * 
 * # Returns
 * 
 * The generated mnemonic phrase (user MUST back this up!)
 * 
 * # Security
 * 
 * - Mnemonic is only returned once
 * - User must save it securely
 * - Seed is encrypted with password and stored in OS keychain
 * 
 * # Example
 * 
 * ```typescript
 * const mnemonic = await invoke('create_wallet', {
 * password: 'my_secure_password',
 * wordCount: 12
 * });
 * console.log('BACKUP THIS MNEMONIC:', mnemonic);
 * ```
 */
async createWallet(password: string, wordCount: string) : Promise<Result<string, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_wallet", { password, wordCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import wallet from BIP-39 mnemonic
 * 
 * Restores a wallet from an existing mnemonic phrase.
 * Derives the specified number of accounts.
 * 
 * # Arguments
 * 
 * * `mnemonic` - BIP-39 mnemonic phrase
 * * `password` - Password for encrypting the seed
 * * `account_count` - Number of accounts to derive (default: 1)
 * 
 * # Returns
 * 
 * List of derived account addresses
 * 
 * # Example
 * 
 * ```typescript
 * const addresses = await invoke('import_wallet', {
 * mnemonic: 'abandon abandon abandon...',
 * password: 'my_secure_password',
 * accountCount: 3
 * });
 * ```
 */
async importWallet(mnemonic: string, password: string, accountCount: number) : Promise<Result<string[], WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_wallet", { mnemonic, password, accountCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unlock wallet with password
 * 
 * Loads all account keys from keychain into memory.
 * Required before performing any operations that need keys.
 * 
 * # Arguments
 * 
 * * `password` - Wallet password
 * 
 * # Example
 * 
 * ```typescript
 * await invoke('unlock_wallet', { password: 'my_password' });
 * ```
 */
async unlockWallet(password: string) : Promise<Result<null, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_wallet", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lock wallet
 * 
 * Clears all keys from memory.
 * User must unlock again to perform key operations.
 * 
 * # Example
 * 
 * ```typescript
 * await invoke('lock_wallet');
 * ```
 */
async lockWallet() : Promise<Result<null, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lock_wallet") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if wallet is locked
 * 
 * # Returns
 * 
 * `true` if wallet is locked, `false` if unlocked
 * 
 * # Example
 * 
 * ```typescript
 * const locked = await invoke('is_wallet_locked');
 * if (locked) {
 * // Show unlock UI
 * }
 * ```
 */
async isWalletLocked() : Promise<Result<boolean, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_wallet_locked") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if wallet exists
 * 
 * # Returns
 * 
 * `true` if wallet has been created, `false` otherwise
 * 
 * # Example
 * 
 * ```typescript
 * const exists = await invoke('wallet_exists');
 * if (!exists) {
 * // Show wallet creation UI
 * }
 * ```
 */
async walletExists() : Promise<Result<boolean, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wallet_exists") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all accounts
 * 
 * Returns list of all accounts (HD and imported).
 * 
 * # Returns
 * 
 * List of accounts with address, name, type, and index
 * 
 * # Example
 * 
 * ```typescript
 * const accounts = await invoke('get_accounts');
 * accounts.forEach(account => {
 * console.log(`${account.name}: ${account.address}`);
 * });
 * ```
 */
async getAccounts() : Promise<Result<AccountExport[], WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create new HD account
 * 
 * Derives the next account from the seed.
 * Wallet must be unlocked.
 * 
 * # Arguments
 * 
 * * `password` - Wallet password (for verification)
 * 
 * # Returns
 * 
 * The newly created account
 * 
 * # Example
 * 
 * ```typescript
 * const account = await invoke('create_account', {
 * password: 'my_password'
 * });
 * console.log('New account:', account.address);
 * ```
 */
async createAccount(password: string) : Promise<Result<AccountExport, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_account", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import account from private key
 * 
 * Imports an account from a private key hex string.
 * Wallet must be unlocked.
 * 
 * # Arguments
 * 
 * * `private_key` - Private key as hex string (with or without 0x prefix)
 * * `name` - Account name
 * * `password` - Wallet password (for verification)
 * 
 * # Returns
 * 
 * The imported account
 * 
 * # Security
 * 
 * - Private key is validated before storage
 * - Private key is encrypted with password
 * - Private key is stored in OS keychain
 * 
 * # Example
 * 
 * ```typescript
 * const account = await invoke('import_account', {
 * privateKey: '0x1234...',
 * name: 'My Imported Account',
 * password: 'my_password'
 * });
 * ```
 */
async importAccount(privateKey: string, name: string, password: string) : Promise<Result<AccountExport, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_account", { privateKey, name, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete account
 * 
 * Removes an account from the wallet.
 * Cannot delete the last account.
 * Wallet must be unlocked.
 * 
 * # Arguments
 * 
 * * `address` - Account address to delete
 * 
 * # Example
 * 
 * ```typescript
 * await invoke('delete_account', {
 * address: '0x1234...'
 * });
 * ```
 */
async deleteAccount(address: string) : Promise<Result<null, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_account", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename an account
 * 
 * Updates the name of an existing account in the wallet and persists it to the keychain.
 * 
 * # Arguments
 * 
 * * `address` - Account address to rename
 * * `newName` - The new name for the account
 * * `password` - Wallet password to authorize modifying the keychain
 * 
 * # Returns
 * 
 * * `Ok(())` - Account renamed successfully
 * * `Err(WalletError)` - If renaming fails, password invalid, or account doesn't exist
 */
async renameAccount(address: string, newName: string, password: string) : Promise<Result<null, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_account", { address, newName, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set active account
 * 
 * Sets the currently active account for the wallet.
 * This account will be used for balance queries, transactions, etc.
 * **PHASE 3.4**: Now emits accountsChanged event to all connected dApp windows.
 * 
 * # Arguments
 * 
 * * `app` - Tauri app handle (for event emission)
 * * `state` - Application state
 * * `address` - Account address to set as active
 * 
 * # Returns
 * 
 * * `Ok(())` - Account set successfully
 * * `Err(WalletError::InvalidAddress)` - Invalid address format
 * * `Err(WalletError::AccountNotFound)` - Account doesn't exist
 * 
 * # Example
 * 
 * ```typescript
 * await invoke('set_active_account', {
 * address: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb'
 * });
 * ```
 */
async setActiveAccount(address: string) : Promise<Result<null, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_account", { address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export wallet mnemonic (seed phrase)
 * 
 * Decrypts and returns the stored BIP-39 mnemonic phrase.
 * Password is required as an authentication gate.
 * 
 * # Security
 * 
 * - Only the correct wallet password grants access
 * - The mnemonic should NEVER be logged or stored outside the app
 * - Show to user once and let them copy it; do not persist in frontend state
 * 
 * # Example (frontend)
 * 
 * ```typescript
 * const mnemonic = await invoke('export_mnemonic', { password: 'my_password' });
 * // Show to user — 12 or 24 space-separated words
 * ```
 */
async exportMnemonic(password: string) : Promise<Result<string, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_mnemonic", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export private key for an account
 * 
 * Returns the raw private key for a specific account.
 * 
 * # Arguments
 * 
 * * `address` - Account address to export
 * * `password` - Wallet password to authorize
 * 
 * # Returns
 * 
 * * `Ok(String)` - Hex encoded private key with 0x prefix
 * * `Err(WalletError)` - If export fails
 */
async exportPrivateKey(address: string, password: string) : Promise<Result<string, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_private_key", { address, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the Railgun Mnemonic
 * 
 * Derives a deterministic 24-word mnemonic specifically for the Railgun Privacy Engine
 * from the wallet's master seed.
 * 
 * # Security
 * 
 * - Requires password to unlock the master seed from the OS keychain.
 * - Sent solely to the secure WebWorker context on the frontend.
 */
async getRailgunMnemonic(password: string) : Promise<Result<string, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_railgun_mnemonic", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the currently focused asset for background monitoring
 * 
 * # Arguments
 * 
 * * `asset` - Asset identifier ("native" or token address)
 */
async setFocusedAsset(asset: string) : Promise<Result<null, WalletError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_focused_asset", { asset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Report user activity (click, keydown, focus). Balance watcher uses this to
 * poll at 3s when active and back off to 5/10/30s when idle.
 */
async reportActivity() : Promise<Result<null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("report_activity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handle dApp request (single entry point)
 * 
 * **PHASE 3.4**: Now extracts window label and origin from Window parameter
 * for proper window-specific validation.
 * 
 * # Security Layers:
 * 1. Window validation (extract label and origin from Window)
 * 2. Rate limiting (prevent spam, per window+origin)
 * 3. Request validation (structure, timestamp)
 * 4. Replay protection (request ID tracking)
 * 5. Session validation (window+origin check)
 * 6. Input sanitization (in rpc_handler)
 * 7. User approval (for sensitive operations)
 * 
 * # Arguments
 * 
 * * `window` - Tauri window (for extracting label and origin)
 * * `state` - Application state
 * * `request` - dApp request
 * 
 * # Returns
 * 
 * * `Ok(DappResponse)` - Request handled
 * * `Err(String)` - Request failed
 * 
 * # Security Notes
 * 
 * - Window label extracted from Window (cannot be spoofed)
 * - Origin extracted from window URL (trusted source)
 * - Session validated per (window_label, origin) pair
 * - Rate limiting per (window_label, origin) pair
 */
async dappRequest(request: DappRequest, origin: string | null) : Promise<Result<DappResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dapp_request", { request, origin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect dApp (create session)
 * 
 * **PHASE 3.4**: Now window-specific
 * 
 * This should be called after user approves connection
 * 
 * # Arguments
 * 
 * * `window` - Tauri window (for extracting label and origin)
 * * `state` - Application state
 * * `name` - dApp name (optional)
 * * `icon` - dApp icon URL (optional)
 * 
 * # Returns
 * 
 * * `Ok(Vec<String>)` - Connected accounts
 * * `Err(String)` - Connection failed
 */
async connectDapp(name: string | null, icon: string | null) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_dapp", { name, icon }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disconnect dApp (remove session)
 * 
 * **PHASE 3.4**: Now window-specific
 * 
 * # Arguments
 * 
 * * `window` - Tauri window (for extracting label and origin)
 * * `state` - Application state
 * 
 * # Returns
 * 
 * * `Ok(())` - Disconnected
 */
async disconnectDapp() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_dapp") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get connected dApps
 * 
 * # Returns
 * 
 * * `Ok(Vec<DappConnection>)` - Connected dApps
 */
async getConnectedDapps() : Promise<Result<DappConnectionExport[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_connected_dapps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disconnect from dApp by origin
 * 
 * Removes all sessions for the given origin across all windows
 * 
 * # Arguments
 * 
 * * `state` - Application state
 * * `origin` - dApp origin to disconnect from
 * 
 * # Returns
 * 
 * * `Ok(())` - Disconnected successfully
 */
async disconnectDappByOrigin(origin: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_dapp_by_origin", { origin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all pending approval requests
 * 
 * # Returns
 * 
 * * `Ok(Vec<ApprovalRequest>)` - All pending approval requests
 */
async getPendingApprovals() : Promise<Result<ApprovalRequest[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pending_approvals") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Respond to an approval request
 * 
 * **PHASE 3.4**: Now emits event to specific dApp window so provider
 * can receive the response.
 * 
 * # Arguments
 * 
 * * `app` - Tauri app handle (for event emission)
 * * `state` - Application state
 * * `response` - Approval response (id, approved, optional data)
 * 
 * # Returns
 * 
 * * `Ok(())` - Response sent successfully
 * * `Err(String)` - If request not found or other error
 */
async respondToApproval(response: ApprovalResponseExport) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("respond_to_approval", { response }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel an approval request
 * 
 * # Arguments
 * 
 * * `state` - Application state
 * * `id` - Request ID to cancel
 * 
 * # Returns
 * 
 * * `Ok(())` - Request cancelled successfully
 * * `Err(String)` - If request not found or other error
 */
async cancelApproval(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_approval", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all pending approval requests
 * 
 * Useful for cleanup/reset during development
 * 
 * # Arguments
 * 
 * * `state` - Application state
 * 
 * # Returns
 * 
 * * `Ok(())` - All requests cleared
 */
async clearAllApprovals() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_approvals") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get performance profiling statistics
 * 
 * Returns performance statistics for all RPC methods including
 * average, min, max durations and request counts.
 * 
 * # Frontend Usage
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/tauri';
 * 
 * const stats = await invoke('get_performance_stats');
 * for (const [method, stat] of Object.entries(stats)) {
 * console.log(`${method}: avg=${stat.avg}ms, count=${stat.count}`);
 * }
 * ```
 */
async getPerformanceStats() : Promise<Result<Partial<{ [key in string]: MethodStats }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_performance_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch external application (e.g., local dApp server)
 * 
 * # Arguments
 * 
 * * `exe_path` - Path to executable to launch
 * 
 * # Returns
 * 
 * * `Ok(())` - Application launched successfully
 * * `Err(String)` - Failed to launch application
 * 
 * # Security
 * 
 * - Only launches executables from whitelisted dApps
 * - Path validation to prevent directory traversal
 * 
 */
async launchExternalApp(exePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_external_app", { exePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handle dApp RPC request via Tauri IPC
 * 
 * This is called from the initialization_script bridge via postMessage.
 * It processes EIP-1193 requests and returns results.
 * 
 * # Arguments
 * 
 * * `state` - Application state
 * * `window_label` - Label of the window making the request
 * * `origin` - Origin of the dApp (e.g., "https://app.uniswap.org")
 * * `method` - RPC method (e.g., "eth_requestAccounts")
 * * `params` - RPC parameters
 * 
 * # Returns
 * 
 * * `Ok(Value)` - RPC result
 * * `Err(String)` - Error message
 * 
 */
async handleDappRequest(windowLabel: string, origin: string, method: string, params: any[]) : Promise<Result<any, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("handle_dapp_request", { windowLabel, origin, method, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open dApp browser in a new window (LEGACY - Phase 3.2)
 * 
 * **DEPRECATED**: Use `open_dapp_url` instead for native WebView.
 * This command opens the old iframe-based browser.
 * 
 * # Arguments
 * 
 * * `app` - Tauri app handle
 * * `url` - Optional dApp URL to load (defaults to test page)
 * 
 * # Returns
 * 
 * * `Ok(())` - Window opened successfully
 * * `Err(String)` - Failed to open window
 */
async openDappBrowser(url: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_dapp_browser", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Legacy command for proxy-mode dApp opening
 * 
 * **DEPRECATED**: Use `open_dapp_window(..., use_proxy: Some(true))` instead.
 */
async openDappUrl(url: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_dapp_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open dApp URL in native WebView window
 * 
 * Creates a new WebView window that loads external URL directly or via proxy.
 * Provider script is injected via initialization_script (bypasses CSP).
 * 
 * # Arguments
 * 
 * * `app` - Tauri app handle
 * * `state` - Application state
 * * `url` - dApp URL to load (must be http:// or https://)
 * * `title` - Optional window title
 * * `use_proxy` - Whether to use the CSP-bypassing proxy (recommended for Opensea, Hyperliquid)
 * 
 * # Returns
 * 
 * * `Ok(String)` - Window label (unique identifier)
 * * `Err(String)` - Failed to create window or invalid URL
 * 
 */
async openDappWindow(url: string, title: string | null, useProxy: boolean | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_dapp_window", { url, title, useProxy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Navigate dApp window to new URL
 * 
 * Updates the URL of an existing dApp window. Validates the new URL
 * and updates the window registry.
 * 
 * # Arguments
 * 
 * * `app` - Tauri app handle
 * * `state` - Application state (for window registry - TODO: Task 1.5)
 * * `window_label` - Window identifier
 * * `url` - New URL to navigate to
 * 
 * # Returns
 * 
 * * `Ok(())` - Navigation successful
 * * `Err(String)` - Window not found or invalid URL
 * 
 * # Security
 * 
 * - URL validation (http/https only)
 * - Window existence check
 * - Origin validation on navigation (prevents redirect attacks)
 * - Window registry updated with new origin
 * 
 * # Example
 * 
 * ```typescript
 * await invoke('navigate_dapp', {
 * windowLabel: 'dapp-123',
 * url: 'https://app.uniswap.org'
 * });
 * ```
 */
async navigateDapp(windowLabel: string, url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("navigate_dapp", { windowLabel, url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close dApp window and clean up resources
 * 
 * Closes the window and performs comprehensive cleanup:
 * - Removes all sessions for the window
 * - Clears all pending approvals for the window
 * - Removes window from registry
 * - Cancels any pending requests
 * 
 * # Arguments
 * 
 * * `app` - Tauri app handle
 * * `state` - Application state (for cleanup)
 * * `window_label` - Window identifier
 * 
 * # Returns
 * 
 * * `Ok(())` - Window closed and cleaned up
 * * `Err(String)` - Window not found or cleanup failed
 * 
 * # Cleanup Steps
 * 
 * 1. Get window by label
 * 2. Clean up sessions for window (SessionManager)
 * 3. Clear approvals for window (ApprovalQueue)
 * 4. Remove from window registry (WindowRegistry - TODO: Task 1.5)
 * 5. Cancel pending requests (TODO: if needed)
 * 6. Close window
 * 
 * # Example
 * 
 * ```typescript
 * await invoke('close_dapp', {
 * windowLabel: 'dapp-123'
 * });
 * ```
 */
async closeDapp(windowLabel: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_dapp", { windowLabel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current URL of dApp window
 * 
 * Returns the current URL being displayed in the dApp window.
 * 
 * # Arguments
 * 
 * * `app` - Tauri app handle
 * * `window_label` - Window identifier
 * 
 * # Returns
 * 
 * * `Ok(String)` - Current URL
 * * `Err(String)` - Window not found or failed to get URL
 * 
 * # Example
 * 
 * ```typescript
 * const url = await invoke('get_dapp_url', {
 * windowLabel: 'dapp-123'
 * });
 * ```
 */
async getDappUrl(windowLabel: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dapp_url", { windowLabel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get transaction history for an address (native + ERC20 token transfers combined)
 */
async getTransactions(address: string, limit: number | null) : Promise<Result<TxRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transactions", { address, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playSound(alert: AlertSound) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_sound", { alert }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSoundConfig(config: SoundConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_sound_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSoundConfig() : Promise<Result<SoundConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sound_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testSound(alert: AlertSound) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_sound", { alert }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
refreshBalanceEvent: RefreshBalanceEvent
}>({
refreshBalanceEvent: "refresh-balance-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Account shape for Specta/TypeScript export (address as string; same JSON shape as Account).
 */
export type AccountExport = { address: string; name: string; account_type: AccountType; index: number | null }
/**
 * Account type
 */
export type AccountType = 
/**
 * HD account (derived from seed)
 */
"hd" | 
/**
 * Imported account (from private key)
 */
"imported"
/**
 * Sound alert types
 */
export type AlertSound = "TransactionIncoming" | "TransactionConfirmed" | "TransactionFailed" | "BalanceIncreased" | "BalanceDecreased" | "LowBalance" | "DappRequest" | "SecurityAlert" | "WalletUnlocked" | "CoinDrop" | { Custom: string }
/**
 * Approval request
 */
export type ApprovalRequest = { 
/**
 * Unique request ID
 */
id: string; 
/**
 * Window label (for routing responses)
 */
window_label: string; 
/**
 * Request type and data
 */
request_type: ApprovalRequestType; 
/**
 * When the request was created
 */
created_at: string }
/**
 * Approval request type
 */
export type ApprovalRequestType = 
/**
 * Connection request
 */
{ type: "connection"; origin: string } | 
/**
 * Transaction request
 */
{ type: "transaction"; origin: string; from: string; to: string; value: string; gas_limit: string | null; gas_price: string | null; data: string | null } | 
/**
 * Message signing request
 */
{ type: "personalSign"; origin: string; address: string; message: string } | 
/**
 * Typed data signing request (EIP-712)
 */
{ type: "signTypedData"; origin: string; address: string; typed_data: string } | 
/**
 * Watch asset request (EIP-747)
 */
{ type: "watchAsset"; origin: string; asset_type: string; address: string; symbol: string; decimals: string; image: string | null } | 
/**
 * Network switch request
 */
{ type: "switchNetwork"; origin: string; chain_id: string } | 
/**
 * Add network request
 */
{ type: "addNetwork"; origin: string; chain_id: string; chain_name: string; rpc_url: string; block_explorer_url: string | null }
/**
 * Approval response shape for IPC/TypeScript (data as AnyJson)
 */
export type ApprovalResponseExport = { id: string; approved: boolean; data: any | null }
/**
 * Balance response
 */
export type BalanceResponse = { 
/**
 * Balance in wei (as string to avoid precision loss)
 */
balance_wei: string; 
/**
 * Balance in ETH (human-readable)
 */
balance_eth: string; 
/**
 * Native token symbol (e.g., "ETH", "PLS")
 */
symbol: string }
/**
 * Build transaction request
 */
export type BuildTransactionRequest = { from: string; to: string; amount: string; gas_limit: string | null; gas_price_gwei: string | null; nonce: string | null; token_address: string | null; data: string | null }
/**
 * Built transaction response
 */
export type BuildTransactionResponse = { from: string; to: string; value: string; gas_limit: string; gas_price: string; nonce: string; chain_id: string; total_cost_eth: string; data: string | null }
/**
 * Supported blockchain types
 */
export type ChainType = 
/**
 * Ethereum Virtual Machine compatible chains
 */
"Evm" | 
/**
 * Stellar network
 */
"Stellar" | 
/**
 * Aptos blockchain
 */
"Aptos" | 
/**
 * Solana network
 */
"Solana" | 
/**
 * Bitcoin network
 */
"Bitcoin"
/**
 * dApp connection shape for IPC/TypeScript (accounts as string list).
 */
export type DappConnectionExport = { window_label: string; origin: string; name: string | null; icon: string | null; accounts: string[]; connected_at: string; last_activity: string; auto_approved: boolean }
/**
 * dApp error structure (EIP-1193 + EIP-1474)
 */
export type DappError = { code: number; message: string; data?: any | null }
/**
 * dApp request structure
 */
export type DappRequest = { id: string; timestamp: string; method: string; params: any[] }
/**
 * dApp response structure
 */
export type DappResponse = { id: string; result?: any | null; error?: DappError | null }
/**
 * Gas estimation response
 */
export type EstimateGasResponse = { 
/**
 * Estimated gas limit
 */
gas_limit: string; 
/**
 * Estimated gas price (in gwei)
 */
gas_price_gwei: string; 
/**
 * Estimated total fee (in ETH)
 */
total_fee_eth: string }
/**
 * Performance statistics for a method
 */
export type MethodStats = { 
/**
 * Number of requests
 */
count: string; 
/**
 * Average duration in milliseconds
 */
avg: string; 
/**
 * Minimum duration in milliseconds
 */
min: string; 
/**
 * Maximum duration in milliseconds
 */
max: string; 
/**
 * Total duration in milliseconds
 */
total: string }
/**
 * Network configuration
 * 
 * Defines all information needed to connect to and interact with a blockchain network.
 */
export type NetworkConfig = { 
/**
 * Unique network identifier (e.g., "ethereum", "pulsechain")
 */
id: string; 
/**
 * Human-readable network name (e.g., "Ethereum Mainnet")
 */
name: string; 
/**
 * Chain type (EVM, Stellar, Aptos, etc.)
 */
chain_type: ChainType; 
/**
 * Chain ID (for EVM chains, this is the EIP-155 chain ID)
 */
chain_id: string; 
/**
 * RPC endpoint URL
 */
rpc_url: string; 
/**
 * Block explorer URL (optional)
 */
explorer_url: string | null; 
/**
 * Native token information
 */
native_token: TokenInfo; 
/**
 * Whether this is a testnet
 */
is_testnet: boolean }
/**
 * Network info response
 */
export type NetworkInfoResponse = { 
/**
 * Network ID
 */
network_id: string; 
/**
 * Network name
 */
name: string; 
/**
 * Chain ID
 */
chain_id: string; 
/**
 * RPC URL
 */
rpc_url: string; 
/**
 * Block explorer URL (empty for now)
 */
explorer_url: string; 
/**
 * Native token information
 */
native_token: TokenInfoResponse }
/**
 * Persisted state shape for IPC/TypeScript (accounts use string address).
 */
export type PersistedStateExport = { version: number; active_network_id: string | null; active_network_rpc: string | null; active_network_chain_id: string | null; active_account: string | null; accounts: AccountExport[]; custom_networks: NetworkConfig[]; tracked_tokens: TrackedToken[]; preferences: UserPreferences }
/**
 * Typed event emitted when balances should be refreshed in the UI.
 */
export type RefreshBalanceEvent = null
/**
 * Send transaction request
 */
export type SendTransactionRequest = { from: string; to: string; amount: string; gas_limit?: string | null; gas_price_gwei: string | null; password: string; token_address: string | null; data: string | null }
/**
 * Sign transaction request
 */
export type SignTransactionRequest = { from: string; to: string; value: string; gas_limit: string; gas_price: string; nonce: string; password: string; data: string | null }
/**
 * Sound configuration
 */
export type SoundConfig = { enabled: boolean; volume: number; sound_pack: string }
/**
 * Network switch request
 */
export type SwitchNetworkRequest = { 
/**
 * Network identifier (e.g., "ethereum-mainnet")
 */
network_id: string; 
/**
 * RPC endpoint URL
 */
rpc_url: string; 
/**
 * Chain ID
 */
chain_id: string }
/**
 * Token balance response
 */
export type TokenBalanceResponse = { balance: string; balance_formatted: string; symbol: string; decimals: number }
/**
 * Token information
 * 
 * Describes a token's basic properties.
 */
export type TokenInfo = { 
/**
 * Token symbol (e.g., "ETH", "PLS")
 */
symbol: string; 
/**
 * Token name (e.g., "Ether", "Pulse")
 */
name: string; 
/**
 * Number of decimals (typically 18 for EVM chains)
 */
decimals: number }
/**
 * Token info for network response
 */
export type TokenInfoResponse = { 
/**
 * Token symbol (e.g., "ETH", "PLS")
 */
symbol: string; 
/**
 * Token name (e.g., "Ethereum", "PulseChain")
 */
name: string; 
/**
 * Token decimals (usually 18)
 */
decimals: number }
/**
 * Token price response
 */
export type TokenPriceResponse = { symbol: string; price_usd: number; timestamp: string }
/**
 * Custom token tracked by the user
 */
export type TrackedToken = { 
/**
 * Token contract address
 */
address: string; 
/**
 * Token symbol (e.g. "WETH", "USDC")
 */
symbol: string; 
/**
 * Token name
 */
name: string; 
/**
 * Token decimals
 */
decimals: number; 
/**
 * Network Chain ID this token belongs to
 */
chain_id: string }
/**
 * Transaction response
 */
export type TransactionResponse = { tx_hash: string; details: BuildTransactionResponse }
/**
 * Transaction record matching the shape expected by HistoryView.tsx
 */
export type TxRecord = { hash: string; from: string; to: string; 
/**
 * Value in human-readable form (e.g. "0.5")
 */
value: string; gas_used: string; gas_price: string; block_number: string; 
/**
 * Unix timestamp (seconds)
 */
timestamp: string; 
/**
 * 1 = success, 0 = failed
 */
status: number; input: string; 
/**
 * Native token symbol (e.g. "PLS", "ETH", "tPLS")
 */
native_symbol: string; 
/**
 * Token symbol — only set for ERC20 transfers (e.g. "USDC")
 */
token_symbol: string | null; 
/**
 * Token contract address — only set for ERC20 transfers
 */
token_address: string | null; 
/**
 * Whether this is an ERC20 token transfer
 */
is_token_transfer: boolean }
/**
 * User preferences
 */
export type UserPreferences = { 
/**
 * Whether sound alerts are enabled
 */
sound_enabled: boolean; 
/**
 * UI theme ("dark" or "light")
 */
theme: string; 
/**
 * Auto-lock timeout in seconds (0 = disabled)
 */
auto_lock_seconds: string; 
/**
 * Default gas multiplier for fee estimation (e.g. 1.2 = 20% buffer)
 */
gas_multiplier: number; 
/**
 * Whether privacy features (Railgun Shadow Engine) are enabled
 */
privacy_enabled: boolean }
/**
 * Transaction validation request
 */
export type ValidateTransactionRequest = { 
/**
 * Recipient address
 */
to: string; 
/**
 * Amount in ETH (human-readable)
 */
amount: string; 
/**
 * Gas limit (optional); accepts string or number from JSON
 */
gas_limit?: string | null; 
/**
 * Token address for ERC20 transfers (optional)
 */
token_address: string | null; 
/**
 * Optional raw transaction data payload (hex string)
 */
data: string | null }
/**
 * Central error type for all wallet operations
 */
export type WalletError = 
/**
 * Network connection failed
 */
{ type: "NetworkError"; message: string } | 
/**
 * RPC request failed
 */
{ type: "RpcError"; message: string } | 
/**
 * Connection timeout
 */
{ type: "ConnectionTimeout"; message: string } | 
/**
 * Invalid address format
 */
{ type: "InvalidAddress"; message: string } | 
/**
 * Invalid checksum
 */
{ type: "InvalidChecksum"; message: string } | 
/**
 * Insufficient balance for transaction
 */
{ type: "InsufficientBalance"; message: { need: string; have: string } } | 
/**
 * Transaction failed
 */
{ type: "TransactionFailed"; message: string } | 
/**
 * Invalid transaction parameters
 */
{ type: "InvalidTransaction"; message: string } | 
/**
 * Gas estimation failed
 */
{ type: "GasEstimationFailed"; message: string } | 
/**
 * Invalid amount
 */
{ type: "InvalidAmount"; message: string } | 
/**
 * Nonce mismatch
 */
{ type: "NonceMismatch"; message: string } | 
/**
 * Account not found
 */
{ type: "AccountNotFound"; message: string } | 
/**
 * Invalid private key
 */
{ type: "InvalidPrivateKey"; message: string } | 
/**
 * Invalid mnemonic phrase
 */
{ type: "InvalidMnemonic"; message: string } | 
/**
 * Derivation path error
 */
{ type: "InvalidDerivationPath"; message: string } | 
/**
 * Unauthorized operation
 */
{ type: "Unauthorized" } | 
/**
 * Wallet is locked
 */
{ type: "WalletLocked" } | 
/**
 * Invalid password
 */
{ type: "InvalidPassword" } | 
/**
 * Encryption failed
 */
{ type: "EncryptionFailed"; message: string } | 
/**
 * Decryption failed
 */
{ type: "DecryptionFailed"; message: string } | 
/**
 * Signer not available (adapter created without signer)
 */
{ type: "SignerNotAvailable"; message: string } | 
/**
 * Signing operation failed
 */
{ type: "SigningFailed"; message: string } | 
/**
 * Key derivation failed (BIP-32)
 */
{ type: "KeyDerivationFailed"; message: string } | 
/**
 * Keyring operation failed (OS keychain)
 */
{ type: "KeyringError"; message: string } | 
/**
 * Chain type not supported
 */
{ type: "ChainNotSupported"; message: string } | 
/**
 * Chain adapter not found
 */
{ type: "AdapterNotFound"; message: string } | 
/**
 * Invalid network configuration
 */
{ type: "InvalidNetwork"; message: string } | 
/**
 * Unsupported network/chain
 */
{ type: "UnsupportedNetwork"; message: string } | 
/**
 * Network not initialized
 */
{ type: "NetworkNotInitialized" } | 
/**
 * No active account selected
 */
{ type: "NoActiveAccount" } | 
/**
 * dApp not connected
 */
{ type: "DappNotConnected"; message: string } | 
/**
 * Permission denied
 */
{ type: "PermissionDenied"; message: string } | 
/**
 * Invalid origin
 */
{ type: "InvalidOrigin"; message: string } | 
/**
 * Origin mismatch (session origin doesn't match request origin)
 */
{ type: "OriginMismatch" } | 
/**
 * Not connected (no active session)
 */
{ type: "NotConnected" } | 
/**
 * Rate limit exceeded
 */
{ type: "RateLimitExceeded" } | 
/**
 * Unsupported method
 */
{ type: "UnsupportedMethod"; message: string } | 
/**
 * Invalid params
 */
{ type: "InvalidParams" } | 
/**
 * Duplicate request
 */
{ type: "DuplicateRequest" } | 
/**
 * Request expired
 */
{ type: "RequestExpired" } | 
/**
 * User rejected the request
 */
{ type: "UserRejected" } | 
/**
 * Configuration error
 */
{ type: "ConfigError"; message: string } | 
/**
 * State persistence error
 */
{ type: "StatePersistenceError"; message: string } | 
/**
 * Internal error (should not happen)
 */
{ type: "InternalError"; message: string } | 
/**
 * Parse error
 */
{ type: "ParseError"; message: string } | 
/**
 * Custom error message
 */
{ type: "Custom"; message: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
